node.software-dsp.rules = [
  {
    matches = [
      { "node.name" = "alsa_output.pci-0000_00_1f.3.analog-stereo" }
    ]

    actions = {
      create-filter = {
        filter-path = "/usr/share/audio-enhancements/latitude-7440/graph.conf"
        # hide-parent = "true"
      }
    }
  }
]

wireplumber.profiles = {
  main = {
    node.software-dsp = required
  }
}