#!/usr/bin/env sh

OLD_REV=$(nix flake metadata --json | jq -r '.locks.nodes.nixpkgs.locked.rev')

nix flake update nixpkgs

NEW_REV=$(nix flake metadata --json | jq -r '.locks.nodes.nixpkgs.locked.rev')

if [ "$OLD_REV" != "$NEW_REV" ]; then
    echo "nixpkgs updated: $OLD_REV -> $NEW_REV"
    echo "Pinning repos to follow nixpkgs revision..."
    nix run github:spikespaz/allfollow -- prune -I

    ./rebuild switch --update && git commit -am "chore: update packages"
    echo "nixpkgs updated: $OLD_REV -> $NEW_REV"

else
    echo "nixpkgs is already up-to-date. No update necessary."
fi
