swipe:
  3:
    left:
      command: "xdotool key ctrl+super+Right" # History forward
      threshold: 0.25
      interval: 0.5
    right:
      command: "xdotool key ctrl+super+Left" # History back
      threshold: 0.25
      interval: 0.5
  4:
    left:
      command: "xdotool key alt+`" # Switch to next workspace
      threshold: 0.1
      interval: 0.75
    right:
      command: "xdotool key alt+shift+`" # Switch to previous workspace
      threshold: 0.05
      interval: 0.75
# pinch:
#   in:
#     command: "xdotool keydown ctrl click 4 keyup ctrl" # Zoom in
#   out:
#     command: "xdotool keydown ctrl click 5 keyup ctrl" # Zoom out
