#! /bin/sh

# xrdb merge ~/.Xresources &

# Set the background color
hsetroot -solid '#1b1c22' &
# Start picom
pgrep -x picom > /dev/null || picom -b --experimental-backends &
# Start polybar
~/.config/polybar/launch.sh &

# Start Simple X hotkey daemon
pgrep -x sxhkd > /dev/null || sxhkd &
# Start touchegg (Trackpad gestures)
# pgrep -x touchegg > /dev/null || touchegg &
touchegg &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width 1
bspc config normal_border_color \#32343d
bspc config focused_border_color \#5294e2

bspc config window_gap 0

bspc config automatic_scheme longest_side
bspc config single_monocle true
bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config focus_follows_pointer true

# Enable mouse for floating windows
# Left click drag to resize
bspc config pointer_action1 move
bspc config pointer_action3 resize_corner

bspc rule -a MultiMC5 state=floating
bspc rule -a android-studio state=floating
bspc rule -a Pavucontrol state=floating rectangle=665x300+1250+28
bspc rule -a SimpleScreenRecorder state=floating rectangle=600x750+1315+28 
bspc rule -a Peek state=floating
bspc rule -a zoom state=floating

# Make X use nice left pointer cursor
xsetroot -cursor_name left_ptr &

# Automatically change the Window classes for floating windows so Picom can use them to decide whether to put a shadow
pgrep -x bspwm_actions > /dev/null || ~/scripts/bspwm_actions.sh shadow_class &
# Start light locker
pgrep -x light-locker > /dev/null || light-locker --no-lock-on-lid --lock-on-suspend &
# Start Ulauncher in the background
pgrep -x ulauncher > /dev/null || ulauncher --no-window-shadow --hide-window &

# Tray icons
# Network/WiFi
pgrep -x nm-applet > /dev/null || nm-applet --indicator &
# Flameshot
pgrep -x flameshot > /dev/null || flameshot &
# KDE Connect
pgrep -x kdeconnect-indi > /dev/null || kdeconnect-indicator &
# Blueman (Bluetooth manager) applet
# pgrep -x blueman-applet > /dev/null || blueman-applet &
# Start Clipboard manager
pgrep -x copyq > /dev/null || copyq &
# Start Notification Daemon
pgrep -x xfce4-notifyd > /dev/null || /usr/lib/xfce4/notifyd/xfce4-notifyd &

# Start keyring daemon
eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK